### ISSUE TITLE
GREAT now supports mm10

### ISSUE THREAD

**Issue by semenko** [jokergoo/rGREAT#1]
Would love to see mm10 supported -- may send a PR in a bit if I have the time.

There are also two new MSigDB ontologies -- not sure if those are included:
http://bejerano.stanford.edu/help/display/GREAT/Version+History

**Comment by jokergoo** [comment]
Thanks for telling this! The new ontologies are automatically added based on the new version of GREAT. But I will change the species settings for the package. I am also thinking to allow users to select the specific version of GREAT (e.g. 3.0, 2.0) to for their analysis.

**Comment by jokergoo** [comment]
Now the package is updated according to the changes on GREAT.

**Comment by semenko** [comment]
Wow, so incredibly fast! Thanks so much! :100: :grinning: :fireworks:
