### ISSUE TITLE
input size restriction problem

### ISSUE THREAD

**Issue by Pickledzebra** [jokergoo/rGREAT#10]
So, while submitting to GREAT via the web-page, one can include up to 1 million genomic regions, rGREAT somehow gets a server-error when the number of genomic regions is over roughly 500K.  

The error is just a generic "failed to submit" which it tries 10 times before exiting.  Not an input format issue.  Strictly size-based.  Same input will work on web page.

**Comment by jokergoo** [comment]
I did not make any restriction on the number of regions in the input that I just simply send the regions to GREAT. The only change I've made is changing to the new url or GREAT. Maybe you were using the old version? Can you try the new version 1.11.1?

**Comment by jokergoo** [comment]
I have a same error when directly submitting to GREAT with more than 1M regions:

<img width="714" alt="screen shot 2018-01-23 at 09 14 28" src="https://user-images.githubusercontent.com/449218/35264651-df4e66e6-001d-11e8-89b1-6158b35e73ea.png">

**Comment by Pickledzebra** [comment]
Yes, but I get that error when I used rGREAT on a test with > 500K (background).

**Comment by Pickledzebra** [comment]
I'm using the latest version.  Perhaps it is not simply the number of genomic regions but the file size?  Is rGREAT inflating the size of the bg and fg sets?

**Comment by Pickledzebra** [comment]
???

**Comment by jokergoo** [comment]
No, the rGREAT package doesn't do anything on the input data. It just simply constructs the HTTP request and submits to GREAT web server automatically. Other other hand, I guess GREAT website does not allow background regions > 500k neither.

**Comment by Pickledzebra** [comment]
The exact same foreground and background dataset will work on the web browser and fail in rGREAT.  It appears to be a dataset size based restriction only present in rGREAT.  The web browser can handle backgrounds with up to 1 million regions.  rGREAT cannot.  This limits the utility of rGREAT, unfortunately.

**Comment by Pickledzebra** [comment]
I have attached an example.  These will work in the web browser and will return a "internal server error" when submitted through rGREAT.

[fore.bed.gz](https://github.com/jokergoo/rGREAT/files/1720673/fore.bed.gz)
[back.bed.gz](https://github.com/jokergoo/rGREAT/files/1720661/back.bed.gz)

**Comment by Pickledzebra** [comment]
I think I've figured out what the issue is.  The web-server tolerates up to a 50Mb file size when you upload .bed files.  The issue with rGREAT is the the object size of the data tables exceeds 50Mb for a much smaller number of genomic regions than do the flat files.  I wonder if there is any way to address this in R?

**Comment by jokergoo** [comment]
Ah, you are right!

In rGREAT I send the regions as a big text instead of a file (because you can send regions either as text or a file) and there is limitation to send plain text through HTTP POST.

Thanks very much and I will update the package accordingly.

**Comment by jokergoo** [comment]
Hi, I found another reason is that you submit the gzip file to GREAT website while rGREAT still sends the file in text format. Nevertheless I have updated the package with saving regions as gzip file and later submit to GREAT. I have tested with your example dataset and everything works fine.

```
# now you can directly use the path of your bed files
> job = submitGreatJob("~/Downloads/fore.bed.gz", bg = "~/Downloads/back.bed.gz", species = "mm10")
> job
Submit time: 2018-02-20 14:16:20
Version: default
Species: mm10
Inputs: 1160 regions
Background: user-defined, 859481 regions
Model: Basal plus extension
  Proximal: 5 kb upstream, 1 kb downstream,
  plus Distal: up to 1000 kb
Include curated regulatory domains

Enrichment tables for following ontologies have been downloaded:
  None
```
