### ISSUE TITLE
retrieve genes associated to phenotypes/diseases

### ISSUE THREAD

**Issue by ilibarra** [jokergoo/rGREAT#12]
Dear jokergoo,

Thanks for developing rGREAT. I have been using it for my analyses and for automation successfully.

Right now, I'd like to retrieve the specific genes associated to certain terms. Currently, the function
```
plotRegionGeneAssociationGraphs(job, ontology='GO Molecular Function', termID='GO:XXXXXXXX')
```

Only accepts ontologies. Is there an option to retrieve programatically the associations to Human Phenotypes / Diseases Ontologies, etc.? By default, this method seems not to work.

If any method already retrieves the full table of termIDs with the gene associations, that would also be very useful.

Thanks for any feedback

Regards,
Ignacio Ibarra

**Comment by jokergoo** [comment]
Sorry I completely missed this issue!

Unfortunately, it is impossible. The GREAT server does not provide a full table of all the terms, so rGREAT cannot download such results.

**Comment by ilibarra** [comment]
No worries. I appreciate the efforts for developing this.

I have recently switched to the GREAT standalone version, so I stopped doing queries to the server with rGREAT. That is only because it helps for knowing all HPO/DISEASE genes listed in the ontologies queried, and for custom calculations.

Regards

**Comment by ceesu** [comment]
Hi, thanks very much for developing this package. I think I am interested in something similar and just want to make sure I'm understanding this correctly. My question is, even though you can download such genes from the online version of great, would you not be able to retrieve which genes correspond to the enrichment terms from rgreat?

When you run the online GREAT with the online version, the page of results contains the same tables that I can retrieve using rGREAT ( "GO Biological Process", etc). When I click on the term it gives tables such as "This term's genomic region-gene association graphs", "This term's genomic region-gene association tables ", etc. The latter lists the genes that correspond to the term and has the option 'Download table as text'.

**Comment by jokergoo** [comment]
By specifying `termID` you can retieve the genes that belong to a specific term.

```r
res = plotRegionGeneAssociationGraphs(job, ontology = "GO Molecular Function",
    termID = "GO:0004984")
```
You can check the text around the last figure in the vignette. http://bioconductor.org/packages/devel/bioc/vignettes/rGREAT/inst/doc/rGREAT.html

**Comment by ceesu** [comment]
Sorry for the late response. This worked for me -- sorry for the misunderstanding.
