### ISSUE TITLE
Cannot use plotRegionGeneAssociationGraphs for specific term ID when using background

### ISSUE THREAD

**Issue by mooratov** [jokergoo/rGREAT#14]
Hello, I am trying to retrieve the table for my enriched term's genomic region-gene association 

This works just fine if i don't specify a background (allow it to be wholeGenome) and use the methodology specified in the tutorial, e.g. 

res = plotRegionGeneAssociationGraphs(job, ontology = "GO_Molecular_Function",
    termID = "GO:0004984")

however, if i run a job with the same foreground region, but use a custom background file, the command does not work, I get the following error and traceback

Error in check_asso_file(f_term): Empty data, probably your 'termID' is invalid.

Traceback:

1. plotRegionGeneAssociationGraphs(job, ontology = "GO Biological Process", 
 .     termID = "GO:0003209")
2. plotRegionGeneAssociationGraphs(job, ontology = "GO Biological Process", 
 .     termID = "GO:0003209")
3. .local(job, ...)
4. check_asso_file(f_term)
5. stop("Empty data, probably your 'termID' is invalid.\n")

note that the enrichment tables look just fine with this configureation, and the command works ok if i don't specify a specific GO term ID.

Thanks

**Comment by jokergoo** [comment]
Hi, can you send me both query regions and background regions to z.gu at dkfz.de? I tried with random regions and it works fine.

**Comment by jokergoo** [comment]
Hi sorry for the late reply. I was on vocation.

I just noticed GREAT website has released a new version (http://great.stanford.edu/public/html/, version 4) and there are some changes for the supported functional catalogs. I am not sure whether this causes your error. I have adjusted the package for the new GREAT version. You can redo you analysis and please report to me if you still have this problem.

**Comment by Amylith** [comment]
Sorry to tag on a little late, but I'm experiencing this same issue.  Here's the code I'm using:

library(rGREAT)

bgdf=read.table("bfbgd.bed", header=T)
sigposdf=read.table("bfsigpos.bed", header=T)

posjob=submitGreatJob(sigposdf, bg=bgdf, species = "hg19")

tbpos = getEnrichmentTables(posjob)

par(mfrow = c(1, 3))
res = plotRegionGeneAssociationGraphs(posjob, ontology = "GO Biological Process",
                                      termID = "GO:0007156")

And the error is: Error in check_asso_file(f_term) : 
  Empty data, probably your 'termID' is invalid.

Just like other people who have posted, the enrichment tables look fine and the term ID I used is present in the GO Biological Process enrichment table.

**Comment by jokergoo** [comment]
It works fine with a randomly generated bed file. Can you send me the bed files you use (to my email address)?

**Comment by ceesu** [comment]
Thanks for your reply, I updated the package so I'm on rGREAT_1.17.1  but it still seems to happen some of the time. I will send files to you.

**Comment by jokergoo** [comment]
Hi @mooratov @ceesu @Amylith , I guess @ceesu has sent me some example datasets (I cann't correspond the name in the email and the username here :)).

According to the test dataset, there is an error when executing `plotRegionGeneAssociationGraphs()` for the GO id `GO:0000076`. If you construct the url for this GO ID, just like other successful GO ids:

http://great.stanford.edu/public-4.0.4/cgi-bin/showTermDetails.php?termId=GO:0000076&ontoName=GOBiologicalProcess&ontoUiName=GO%20Biological%20Process&sessionName=20190906-public-4.0.4-N0wDve&species=mm9&foreName=file4388604d634b.gz&backName=file438878b20251.gz&table=region

@ceesu people can not access you original peak files with above link, so I put this link public.

You will find there is no result for this GO id on the GREAT website neither, which means, this is a problem of GREAT web service while not rGREAT package.

If you run `plotRegionGeneAssociationGraphs()` in a loop, I suggest you to use `try()` to capture this error while not break the loop.

**Comment by ceesu** [comment]
I see, thanks so much for looking into this! I will try your suggestion.
