### ISSUE TITLE
termID = "GO:0007165" for signal transduction is not working

### ISSUE THREAD

**Issue by bharati16mehani** [jokergoo/rGREAT#17]
Hi I am using 
`submitGreatJob(job, species = "hg19",version = "3.0.0")`
and
`tb = getEnrichmentTables(job, ontology = "GO Biological Process",termID = "GO:0007165")`

but getting an error

Error in check_asso_file(f_term) : Empty data, probably your 'termID' is invalid.

And tried the same with other termID like 
`tb = plotRegionGeneAssociationGraphs(job, ontology = "GO Biological Process",termID = "GO:0004984")`

and getting the same error:

Error in check_asso_file(f_term) : Empty data, probably your 'termID' is invalid.

Can you please look into the matter and help?

**Comment by jokergoo** [comment]
Hi, maybe you can check https://github.com/jokergoo/rGREAT/issues/14#issuecomment-528997950
