### ISSUE TITLE
use MSigDB database with rGREAT tool 

### ISSUE THREAD

**Issue by andreaT87** [jokergoo/rGREAT#18]
Dear rGREAT tool providers, 

This is Andrea Terrasi (PhD student at LMU in Munich).
I am working with your tool (last version) and for my data (mm10 genome) I don't have the possibility to use the MSigDB database as "available ontologies".

How is it possible? how can I select the MSigDB with your package
Thank you for your support

**Comment by andreaT87** [comment]
to better explain, I am going to attach the script:

head(sign_atac_sig1)
   chr     start       end
1 chr1 107488351 107488527
2 chr1 107748797 107748953
3 chr1 118449422 118449734
4 chr1 125496866 125497070
5 chr1 127261095 127261323
6 chr1 127357884 127358097
>
        > job_1 = submitGreatJob(sign_atac_sig1, bg = NULL,
+                        species = "mm10",
+                            includeCuratedRegDoms = TRUE,
+                            rule = "basalPlusExt",
+                            adv_upstream = 250.0,
+                            adv_downstream = 250.0,
+                            adv_span = 250.0,
+                            request_interval = 10,
+                            max_tries = 10,
+                            version = "4.0.4")
Warning message:
In submitGreatJob(sign_atac_sig1, bg = NULL, species = "mm10", includeCuratedRegDoms = TRUE,  :
  GREAT gives a warning:
Your set hits a large fraction of the genes in the genome, which often
does not work well with the GREAT Significant by Both view due to a
saturation of the gene-based hypergeometric test.

See our tips for handling large datasets or try the Significant By
Region-based Binomial view.

> availableCategories(job_1)
[1] "GO"        "Phenotype" "Genes"

###################
I hope that this could be usefoul.
Thank you again for your suppoty

Best regards,
Andrea Terrasi

**Comment by jokergoo** [comment]
I guess you need to use GREAT version 3.0.0. In 4.0.4, they remove quite a lot ontologies. See http://great.stanford.edu/help/display/GREAT/Version+History

You can use the old version of GREAT by sepcifying `version = '3'`.

**Comment by andreaT87** [comment]
Dear Zuguang Gu, 
Thank you so much for your reply 

Best,
Andrea
