### ISSUE TITLE
GREAT has more statistical columns that aren't visible

### ISSUE THREAD

**Issue by semenko** [jokergoo/rGREAT#2]
I'm trying to sort & filter data based on some other columns that GREAT provides (e.g. BinomFdrQ & HyperBonfP / HyperFdrQ).

I don't see these in the current output of rGREAT -- perhaps they could be added? (They might be new in 3.0)

It looks like the output is:
Ontology      ID      Desc    BinomRank       BinomP  BinomBonfP      BinomFdrQ       RegionFoldEnrich        ExpRegions      ObsRegions      GenomeFrac      SetCov  HyperRank       HyperP  HyperBonfP      HyperFdrQ       GeneFoldEnrich  ExpGenes        ObsGenes        TotalGenes      GeneSetCov      TermCov Regions Genes

**Comment by jokergoo** [comment]
For these columns, although they are provided in the HTML table, but they are not available in the JSON file which rGREAT uses (only raw p-values are provided in the JSON file). However, it is easy to calculate these adjusted p-values in R. e.g. to get the FDR, use `p.adjust(tb$BinomP, method = "BH")`, to get the Bonferroni corrected p-value, use `p.adjust(tb$BinomP, method = "bonferroni")`.

**Comment by semenko** [comment]
Awesome -- many thanks! (I saw them from the raw curl "interface" at http://bejerano.stanford.edu/help/display/GREAT/Programming+Interface )
