### ISSUE TITLE
can't retrieve genes per categories using download_by argument

### ISSUE THREAD

**Issue by Brawni** [jokergoo/rGREAT#21]
Hello! 

Thanks for the package! I can't seem to make it work to get the list of genes associated to each GO term as the argument: download_by its not recognized in the function getEnrichmentTables.

Thank you!

**Comment by jokergoo** [comment]
What is the version of the package you are using? I think it should be higher than 1.19.1.

https://github.com/jokergoo/rGREAT/blob/5d95b7a837c7dbe1327d74d0ad777a4e0b5d023d/NEWS#L1-L4

**Comment by Brawni** [comment]
Hi jokergoo!

Yes sorry my mistake I was working with version 1.18. I installed version 19.2 from GitHub but from Bioconductor I was getting version 1.18.

Thanks a lot!
