### ISSUE TITLE
Retrieving plots from the plotRegionGeneAssociationGraphs function

### ISSUE THREAD

**Issue by peranti** [jokergoo/rGREAT#23]
Hello @jokergoo,

Thanks for creating this package to use the GREAT tool.

What possibilities are available to access the plot (object) generated by the function `plotRegionGeneAssociationGraphs`? 

I could only notice the output as a _GRanges_ object, with _gene_, _distTSS_ as the columns.

**Comment by jokergoo** [comment]
You cannot see the plot? 

Did you forget to close the previous failed graphics devices?

Try to type `dev.off()` several times.

Or are you in a platform with no graphic supported?

**Comment by peranti** [comment]
_Sorry for being unclear._

I could see the plot generated with the function `plotRegionGeneAssociationGraphs` in the plot area. However, I am interested in extracting the plot details from the output object instead of the plot area. I wish to use them for further manipulation.

**Comment by jokergoo** [comment]
What do you mean the "details". The function returns a `GRanges` object and that is basically everything returned from GREAT website.

**Comment by peranti** [comment]
_I will try to be more clear, atleast this time._

The `plotRegionGeneAssociationGraphs` returns a `GRanges` object `res` with the data fetched from GREAT into two columns: `gene`, `distTSS`.  An example would be as follows: 

```
res = plotRegionGeneAssociationGraphs(job)
res
```
The function also provides an option not to generate the plot using the `plot` argument `plot = FALSE`.
```
res = plotRegionGeneAssociationGraphs(job, plot = FALSE)
res
```
I Hope, I understood it correctly.

For my use case, I am making multiple calls using a loop function. If I try to use the first command which generates the plot, how could I print the plot for each loop call after the loop ends? 

Let's say, I run the loop with 10 instances with `request_interval = 600` between each instance, the process generates 10 plots during the processing. How can I see all these 10 plots once the loop process completes or how can I compare or print them?

I couldn't use the function like `last_plot()` to fetch the plot and store it in a variable and maybe save it for future use.

**Comment by jokergoo** [comment]
Ah, I see. Then I suggest you directly save the plots in a pdf.

```r
pdf(...)
for(i in 1:10) {
    plotRegionGeneAssociationGraphs(...)
}
dev.off()
```
