### ISSUE TITLE
Ensembl IDs

### ISSUE THREAD

**Issue by rjoana1** [jokergoo/rGREAT#27]
Hello,
thank you very much for your tool.
I've been using GREAT to annotate my chip-seq peak regions and enrichment analysis.
I've noticed that there is no Ensembl ID associated with the gene name on tables "all genomic region-gene associations".
I've tried to get these IDs by retrieving the table "All data as .tsv" when chosing on "Global controls" the option "Ensembl Genes". But the content on ID row does not retrieves an output when searching on Ensembl. Even when clicking directly on the ID link (web version, ignoring statistical significance) it does not correpond to the gene identified.
(Job ID: 20211022-public-4.0.4-akUthk)

I really need the Ensembl IDs from the genes associated with my chip-seq data to pursue my work. I'd like very much to learn how to retrieve them: either by Great web tool or rGREAT.

I thank you in advance.

**Comment by rjoana1** [comment]
> 
> 
> Hello, thank you very much for your tool. I've been using GREAT to annotate my chip-seq peak regions and enrichment analysis. I've noticed that there is no Ensembl ID associated with the gene name on tables "all genomic region-gene associations". I've tried to get these IDs by retrieving the table "All data as .tsv" when chosing on "Global controls" the option "Ensembl Genes". But the content on ID row does not retrieves an output when searching on Ensembl. Even when clicking directly on the ID link (web version, ignoring statistical significance) it does not correpond to the gene identified. (Job ID: 20211022-public-4.0.4-akUthk)
> 
> I really need the Ensembl IDs from the genes associated with my chip-seq data to pursue my work. I'd like very much to learn how to retrieve them: either by Great web tool or rGREAT.
> 
> I thank you in advance.

I have solved the issue using a different strategy. The issue reported still persists.

**Comment by jokergoo** [comment]
I think there are many tools that do Gene ID conversion. It is not difficult to use them to convert from gene symbols to Ensembl IDs.
