### ISSUE TITLE
hg38 not available for version 2.0 or 3.0

### ISSUE THREAD

**Issue by TerezaClarence** [jokergoo/rGREAT#28]
Dear developers,

thank you for this great packages! I was wondering, is there a way how to set hg38? I get error messages that only hg18 and hg19 are available for versions 3.0 or 2.0. 

Thank you so much.

Best regards,
Tereza Clarence

**Comment by jokergoo** [comment]
Yes, only GREAT v4.0.4 supports hg38. http://great.stanford.edu/great/public-4.0.4/html/
