### ISSUE TITLE
rGREAT against scaffold / unassembled chromosomes

### ISSUE THREAD

**Issue by MafGal** [jokergoo/rGREAT#30]
Dear @jokergoo 

I am working with zebrafish and version 3.0 of GREAT, which allows to use the zebrafish genome version danRer7.
It contains some scaffold (e.g. Zv9_scaffold3485) or unassembled chromosome names, which give an error when running rGREAT:
`Chromosome names (in `gr`) should have 'chr' prefix.`
I tried adding the prefix "chr" to those names, but it still failed.

If I run GREAT online with the same input sequences, it runs with no error and assigns genes within scaffolds.
Do you have any idea for this error in rGREAT or suggestion for how to circumvent it without having to run GREAT online?

Thank you very much in advance for your input.
Greetings,
Mafalda.

**Comment by jokergoo** [comment]
The new version will be updated on GitHub today or tomorrow.

**Comment by MafGal** [comment]
Thanks a lot for updating! :)
Then I think rGREAT will give exactly the same genes assigned to regions as the online version, which is great. I will check it to confirm in the new version, many thanks, it makes things a lot easier and quicker :)

**Comment by jokergoo** [comment]
Updated!

**Comment by MafGal** [comment]
Dear @jokergoo 

I can run rGREAT for zebrafish danrer7 (GREAT v3) without getting errors regarding chromosomes which do not contain "chr" in the name.
When I do `res = plotRegionGeneAssociationGraphs(job)` I get the plots as expected; the 2 last ones are identical to GREAT online; the 1st one looks a bit different but as far as I can see is correct.

However, I am not able to get the results; `res` is NULL and I can not access the region-gene / gene to region associations.
Previously it worked, so I'm wondering what's going wrong now?

Will be great if you can give me a hand or suggest something to try out.

Thank you advance,
Mafalda.

**Comment by MafGal** [comment]
Thank you! :)
