### ISSUE TITLE
Explanation of result columns

### ISSUE THREAD

**Issue by dktanwar** [jokergoo/rGREAT#35]
Hi @jokergoo 

Thanks for `rGREAT`, extremely useful.

I was looking into difference between `p_value` and `p_value_hyper`, but I was not able to find it in the vignette. Could you please help me with this?

| id         | description                             | genome_fraction | observed_region_hits | fold_enrichment | p_value     | p_adjust    | mean_tss_dist | observed_gene_hits | gene_set_size | fold_enrichment_hyper | p_value_hyper | p_adjust_hyper |
|------------|-----------------------------------------|-----------------|----------------------|-----------------|-------------|-------------|---------------|--------------------|---------------|-----------------------|---------------|----------------|
| GO:0042254 | ribosome biogenesis                     | 0.01304709      | 4                    | 7.861071097     | 0.001655518 | 0.346003327 | 4116          | 3                  | 6             | 2.756410256           | 0.075978557   | 1              |
| GO:0022613 | ribonucleoprotein complex biogenesis    | 0.01615005      | 4                    | 6.350698889     | 0.003565088 | 0.372551657 | 4116          | 3                  | 7             | 2.362637363           | 0.115906015   | 1              |
| GO:0022607 | cellular component assembly             | 0.01097845      | 3                    | 7.006733622     | 0.009006156 | 0.470571658 | 3775          | 2                  | 7             | 1.575091575           | 0.37186203    | 1              |
| GO:0065003 | protein-containing complex assembly     | 0.01097845      | 3                    | 7.006733622     | 0.009006156 | 0.470571658 | 3775          | 2                  | 5             | 2.205128205           | 0.224480679   | 1              |
| GO:0043933 | protein-containing complex organization | 0.015571808     | 3                    | 4.939893788     | 0.022744111 | 0.950703858 | 3775          | 2                  | 6             | 1.837606838           | 0.29873174    | 1              |
| GO:0006364 | rRNA processing                         | 0.008926099     | 2                    | 5.74518061      | 0.047484017 | 1           | 4916          | 2                  | 5             | 2.205128205           | 0.224480679   | 1              |

**Comment by dktanwar** [comment]
Found them here: https://great-help.atlassian.net/wiki/spaces/GREAT/pages/655456/Statistics

**Comment by liboxun** [comment]
Echoing @dktanwar, thanks for `rGREAT` @jokergoo!

I had the same exact question, and I'm so glad to find the answer here. However, it'd still be very useful if descriptions of what each result column means are included in the documentation of `rGREAT`.
