### ISSUE TITLE
error when providing background set

### ISSUE THREAD

**Issue by yzhang12** [jokergoo/rGREAT#7]
Hi,

I don't understand why I always have problem using my own background with rGREAT: 

Error in submitGreatJob(reg7.hg19.1.bed, bg = erg.ctl.hg19.1.bed, version = "3.0") : 
  GREAT encountered a user error:
The foreground set is not a subset of the background set. GREAT requires each foreground element to be
reproduced exactly within the background set.

I checked that my foreground was indeed a subset of the background using findoverlaps(type="equal"). And using the same set on Great website didn't cause this error.

**Comment by jokergoo** [comment]
Hi,

Which version are you using? I always have problems with understanding the `background` settings with GREAT and in recent versions I changed the package a little bit.

If possible, would you send me the regions and the background to me so that I can test on them?

Thanks!

**Comment by yzhang12** [comment]
I just found the old posts and updated to the latest version, but now I got another error:
Error in .Method(..., deparse.level = deparse.level) : 
  number of columns for arg 2 do not match those of first arg

**Comment by jokergoo** [comment]
Hi, I think this is a problem of the old version of the package. I tested it with version 1.3.3 and it works fine. You can update the package by `devtools::install_github("jokergoo/rGREAT")`

**Comment by yzhang12** [comment]
Thank you!
