### ISSUE TITLE
Latest Version Causes Error with Background Set

### ISSUE THREAD

**Issue by imk1** [jokergoo/rGREAT#8]
I installed the latest version of rGREAT by running devtools::install_github("jokergoo/rGREAT").

I tried to submit a job to GREAT by running job = submitGreatJob(bed, bg=background, species="hg19", bgChoice="data").

I got the following error:
Error in .Method(..., deparse.level = deparse.level) : 
  number of columns for arg 2 do not match those of first arg

bed and background each have 3 columns (I checked this using ncol to be sure).  Do you know what I might be able to do to fix this problem?  Thanks!

**Comment by jokergoo** [comment]
Can you also sent me the message from `traceback()`? and also the results from `head(bed)` and `head(background)`?

**Comment by imk1** [comment]
Here is head(bed):
     V1       V2       V3
    V1     V2     V3
1 chr1 839949 840357
2 chr1 859045 859619
3 chr1 860160 860457
4 chr1 875519 876039
5 chr1 876973 877680
6 chr1 895787 896872

Here is head(background):
    V1     V2     V3
1 chr1 521497 521667
2 chr1 565226 565412
3 chr1 569315 569501
4 chr1 713854 714383
5 chr1 762393 762557
6 chr1 762605 763202

Here is the output from traceback():
15: stop("number of columns for arg ", i, " do not match those of first arg")
14: .Method(..., deparse.level = deparse.level)
13: eval(expr, envir, enclos)
12: eval(.dotsCall, env)
11: eval(.dotsCall, env)
10: standardGeneric("rbind")
9: (function (..., deparse.level = 1) 
   standardGeneric("rbind"))(<S4 object of class "DataFrame">, <S4 object of class "DataFrame">)
8: do.call(rbind, lapply(x, mcols, FALSE))
7: do.call(rbind, lapply(x, mcols, FALSE))
6: .unlist_list_of_GenomicRanges(args, ignore.mcols = ignore.mcols)
5: .local(x, ..., recursive = recursive)
4: c(gr, setdiff(bg, gr))
3: c(gr, setdiff(bg, gr))
2: sort(c(gr, setdiff(bg, gr)))
1: submitGreatJob(bed, bg = background, species = "hg19", bgChoice = "data")

I tried going through the code step-by-step on the command line, and it seems like this line might be causing the problem: https://github.com/jokergoo/rGREAT/blob/master/R/great.R#L179

**Comment by jokergoo** [comment]
This is a bug caused by the new version of bioconductor packages. I have fixed it. Now you can install the newest version from Github:

```
devtools::install_github("jokergoo/rGREAT")
```

Thanks for reporting this!

**Comment by imk1** [comment]
Thank you so much for getting this fixed.  Everything seems to be working now.
