### ISSUE TITLE
help please?

### ISSUE THREAD

**Issue by Pickledzebra** [jokergoo/rGREAT#9]
Hello,

I'm in the position of needing to run quite a few GREAT jobs and thought your package would be life-saver in doing this.  However, I am at a complete loss as to why I can't get it to work.  I believe I have all the necessary packages installed and I've ensured that I can postForm to the GREAT server.

When I try your simplest example, I get the following:

> set.seed(123)
> bed=circlize::generateRandomBed(nr=1000,nc=0)
> head(bed)
   chr    start      end
1 chr1   155726  2608935
2 chr1  6134977 10483365
3 chr1 11354986 11423447
4 chr1 15134641 19115321
5 chr1 22692774 23328609
6 chr1 23639094 25639077
> job=submitGreatJob(bed)
Error : Not Found

Error : Not Found

failed with the request, try after 5 min (1th try)

I haven't got the foggiest idea where it is failing.

Thanks!

**Comment by jokergoo** [comment]
Are you using the newest version of the package? GREAT website recently changed the path of the tool.

```{r}
library(devtools)
install_github("jokergoo/rGREAT")
```

**Comment by Pickledzebra** [comment]
That worked.  Thank you so much!  However, now I get:

Error in .Primitive("c")(<S4 object of class "Rle">, <S4 object of class "Rle">) : 
  could not find symbol "recursive" in environment of the generic function

**Comment by jokergoo** [comment]
OK, I think the problem is `back` the background you have. Would you mind send me the objects of `fore` and `back` to that I can have a test?

**Comment by Pickledzebra** [comment]
Yes here they are.  

[ForeBack.RData.gz](https://github.com/jokergoo/rGREAT/files/1544704/ForeBack.RData.gz)

**Comment by Pickledzebra** [comment]
Any luck with those examples?

**Comment by jokergoo** [comment]
Strange, I haven't see this error before. With your data, it works fine at my laptop:

```
> job = submitGreatJob(fore, bg = back, species = "mm10")
Submit time: 2017-12-13 17:26:47
Version: default
Species: mm10
Background: data
Model: Basal plus extension
  Proximal: 5 kb upstream, 1 kb downstream,
  plus Distal: up to 1000 kb
Include curated regulatory domains

Enrichment tables for following ontologies have been downloaded:
  None
> tb = getEnrichmentTables(job)
> length(tb)
[1] 3
> names(tb)
[1] "GO Molecular Function" "GO Biological Process" "GO Cellular Component"
> dim(tb[[1]])
[1] 3489   13
```

The version of `rGERAT` I use is 1.11.1

**Comment by Pickledzebra** [comment]
Ok.  So it's some conflict with something else in my R installation, I'm guessing.  Thanks so much for the help!
